version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    dns: 8.8.8.8
    environment:
      - HOST=0.0.0.0 # Pastikan container mendengarkan di semua alamat
      - NODE_ENV=production
      - NEXT_PUBLIC_API_HOST=${{secrets.NEXT_PUBLIC_API_HOST}}
      - NEXT_PUBLIC_API_PORT=${{secrets.NEXT_PUBLIC_API_PORT}}
      - X_API_KEY=${{secrets.X_API_KEY}}
      - BASE_URL=${{secrets.BASE_URL}}
      - MEDIN_URL=${{secrets.MEDIN_URL}}
      - X_API_KEY_MEDIN=${{secrets.X_API_KEY_MEDIN}}
      - CONS_ID=${{secrets.CONS_ID}}
      - SECRETKEY=${{secrets.SECRETKEY}}

    networks:
      - app_network
    stdin_open: true
    tty: true
    restart: always
    command: ["npx", "next", "start", "-p", "3001", "-H", "0.0.0.0"]

networks:
  app_network:
    driver: bridge