import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import socket from "@/app/utils/api/socket";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Farmasi BPJS",
   icon: '/logo_crop.png',     // Main icon (PNG/SVG)
    shortcut: '/logo_crop.png', // Alternate
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
