version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_container_farmasi_TEST
    dns: 8.8.8.8 
    ports:
      - "5002:5001"
    environment:
      - X_API_KEY=${{secrets.X_API_KEY}}
      - BASE_URL=${{secrets.BASE_URL}}
      - HOST=${{secrets.HOST}}
      - PORT=${{secrets.PORT}}
      - FE_HOST=${{secrets.FE_HOST}}
      - FE_PORT=${{secrets.FE_PORT}}
      - MEDIN_URL=${{secrets.MEDIN_URL}}
      - MEDIN_URL2=${{secrets.MEDIN_URL2}}
      - MEDIN_URL_GMCB=${{secrets.MEDIN_URL_GMCB}}
      - X_API_KEY_MEDIN=${{secrets.X_API_KEY_MEDIN}}
      - CONS_ID=${{secrets.CONS_ID}}
      - PASSWORD=${{secrets.PASSWORD}}
      - CONS_ID_FARMASI=${{secrets.CONS_ID_FARMASI}}
      - SECRETKEY=${{secrets.SECRETKEY}}
      - API_URL=${{secrets.API_URL}}
      - API_WA=${{secrets.API_WA}}
      - CONS_ID_WA=${{secrets.CONS_ID_WA}}
      - PASSWORD_WA=${{secrets.PASSWORD_WA}} 
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=farmasi_queue_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - farmasi_network
    restart: always

  db:
    image: mysql:8.0
    container_name: mysql_container_farmasi_TEST
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: farmasi_queue_db
    volumes:
      - mysql_data_farmasi:/var/lib/mysql
    networks:
      - farmasi_network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root --password=secret || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container_farmasi_TEST
    ports:
      - "3301:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: secret
    depends_on:
      - db
    networks:
      - farmasi_network
    restart: always

networks:
  farmasi_network:
    driver: bridge

volumes:
  mysql_data_farmasi:
  redis_data:
